[connections.snowflake]
account = "GHGGWAG.PPB35617"
user = "ACME_ADMIN"
password = "Temp1234562222"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
